owen-it/laravel-auditing-doc

installation.md
Changes 'php atisan' to 'php artisan'
=> Minor typo update

general-settings.md
=> Removed reference to Authentication Model

getting-audits.md
Changed `$team->audits->with('user');` to `$team->audits()->with('user')->get();`
=> Eager loading of the user : syntax correction

audit-drivers.md, auditor.md, behavior-settings.md, general-settings.md, installation.md, introduction.md
Some last minute documentation updates.
=> Last v4 updates

audit-presentation.md, auditor.md, behavior-settings.md, events.md, general-settings.md, getting-audits.md, installation.md, introduction.md
Reworked the documentation with better examples and simplifying text.
=> Updates for final v4

.gitignore, audit-presentation.md, getting-audits.md, installation.md, license.md
Updates to reflect changes done to the development version of the package.
=> Documentation updates

README.md, documentation.md, troubleshooting.md, upgrade.md
Added a troubleshooting section to the documentation.
=> troubleshooting

troubleshooting.md
Minor updates to the troubleshooting document.
=> Troubleshooting updates

README.md, documentation.md, general-settings.md, troubleshooting.md, upgrading.md
Added a section with upgrading instructions.
=> [4.0] Upgrading

transform-audit.md
Fix a minor error in the transform example.
=> fix(Audit): transform example

audit-presentation.md, getting-audits.md, troubleshooting.md
Minor updates to the documentation to reflect the changes in 4.0.4
=> Updates for 4.0.4

getting-audits.md, troubleshooting.md, upgrading.md
- Added instructions to upgrade from [4.0.0, 4.0.3] to 4.0.4+
- Added `Closure` issue entry in **Troubleshooting**
=> Documentation updates for v4

behavior-settings.md, introduction.md, transform-audit.md, troubleshooting.md
Work done in this PR:
- Remove wrong semicolon from examples
- Add troubleshooting entry about using UUID instead of INT / AUTO-INCREMENT
- Add troubleshooting entry about wrong attribute updates in an `Audit`
=> [4.0] Updates

troubleshooting.md
- Fix `find()` example in the troubleshooting section.
=> [4.0] quick fix

audit-implementation.md, installation.md, troubleshooting.md, upgrading.md
Updated the audit implementation entry.
=> Audit Implementation

audit-presentation.md, getting-audits.md, troubleshooting.md
Updated some examples to reflect the changes made in the new version.
=> Minor updates

upgrading.md
=> Upgrade guide

audit-drivers.md, audit-events.md, audit-implementation.md, audit-presentation.md, audit-tags.md, audit-transformation.md, auditable-configuration.md, auditable-transition.md, auditor.md, documentation.md, general-configuration.md, getting-audits.md, installation.md, model-setup.md, problems.md, troubleshooting.md, upgrading.md
Updates to the documentation for version 5.0.
=> [V5] Documentation

audit-drivers.md, audit-implementation.md, auditable-configuration.md, auditable-transition.md, auditor.md, general-configuration.md, getting-audits.md, installation.md, troubleshooting.md, upgrading.md
Hopefully, the last updates before V5.
=> [V5] minor updates

audit-migration.md, audit-resolvers.md, auditable-configuration.md, documentation.md, general-configuration.md, installation.md, troubleshooting.md, upgrading.md
Updated documentation for version 6.0.
=> Version 6.0

audit-resolvers.md, audit-tags.md, auditable-configuration.md, auditable-transition.md, troubleshooting.md
=> [V6] Some more updates

auditable-configuration.md
Document auditing quick enable/disable feature.
=> feat(auditable-configuration): add enable/disable documentation

audit-drivers.md
Features:
- Save Audits to Elasticsearch
- Push audits to queue, saves time for realtime applications
=> Added Support for Elasticsearch Driver

audit-resolvers.md
fixes https://github.com/owen-it/laravel-auditing/issues/446
=> docs(resolver): add a tip to the User resolver

installation.md
The v9.0 is only compatible with Laravel >=5.8.
=> Laravel compatibility

auditable-configuration.md
Changes to use more inclusive language to move away from white/black and master/slave language across the IT spectrum.
=> Use more inclusive language

general-configuration.md
Laravel Sanctum users will appreciate this
=> Update general-configuration.md for Sanctum users

auditable-configuration.md
=> Corrected spelling error in auditable-configuration.md

README.md, attribute-modifiers.md, audit-migration.md, auditable-configuration.md, general-configuration.md, installation.md, model-setup.md, problems.md, troubleshooting.md, upgrading.md
adds .md to all internal links so that they don't resolve to a 404
=> md additions

installation.md
Thanks for the awesome gift to the laravel community. it would be good if add this video link in the description.  it would be helpful to beginner
=> docs: Video Tutorial add
